#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ZXing.Net.Mobile.Forms.Android.Resource", IsApplication=false)]

namespace ZXing.Net.Mobile.Forms.Android
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}

		public partial class Layout
		{
			// aapt resource value: 0x7f030030
			public static int zxingscanneractivitylayout = 2130903088;
			
			// aapt resource value: 0x7f030031
			public static int zxingscannerfragmentlayout = 2130903089;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			// aapt resource value: 0x7f050020
			public static int library_name = 2131034144;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
	}
}
#pragma warning restore 1591
