//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZxingSharp.MonoForAndroid.Sample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int buttonScanCustomView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int buttonScanDefaultView = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int buttonZxingFlash = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout2 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ZxingOverlay = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
